/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as MarchesRouteImport } from './routes/marches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsIdRouteImport } from './routes/produits.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesRoute = MarchesRouteImport.update({
  id: '/marches',
  path: '/marches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIdRoute = ProduitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProduitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/marches': typeof MarchesRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/services': typeof ServicesRoute
  '/produits/$id': typeof ProduitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/marches': typeof MarchesRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/services': typeof ServicesRoute
  '/produits/$id': typeof ProduitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/marches': typeof MarchesRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/services': typeof ServicesRoute
  '/produits/$id': typeof ProduitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/marches'
    | '/produits'
    | '/services'
    | '/produits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/marches'
    | '/produits'
    | '/services'
    | '/produits/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/marches'
    | '/produits'
    | '/services'
    | '/produits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  MarchesRoute: typeof MarchesRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches': {
      id: '/marches'
      path: '/marches'
      fullPath: '/marches'
      preLoaderRoute: typeof MarchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$id': {
      id: '/produits/$id'
      path: '/$id'
      fullPath: '/produits/$id'
      preLoaderRoute: typeof ProduitsIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
  }
}

interface ProduitsRouteChildren {
  ProduitsIdRoute: typeof ProduitsIdRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsIdRoute: ProduitsIdRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  MarchesRoute: MarchesRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
